In [101]:
import matplotlib.pyplot as plt
from sklearn import linear_model
import numpy as np
from sklearn.metrics import mean_squared_error, r2_score
import pandas as pd
import eli5
train = pd.read_csv('/Users/walkerrowe/Documents/keras/votes.csv',usecols=['Trump','White','Black','Hispanic','age65plus','Edu_highschool','SEX255214'])
all = pd.read_csv('/Users/walkerrowe/Documents/keras/votes.csv')
 
reg = linear_model.LinearRegression()
model=reg.fit(xx,yy)
print('Coefficients: \n', reg.coef_)
perm = PermutationImportance(reg, random_state=1).fit(xx, yy)
eli5.show_weights(perm)

Coefficients: 
 [[ 0.51503519 -0.13783668 -0.44485146  0.00352575 -0.00985589 -0.00801731]]


Coefficients: 
 [[ 0.51503519 -0.13783668 -0.44485146  0.00352575 -0.00985589 -0.00801731]]


In [93]:
xx

    
    

array([[7.79e-01, 1.87e-01, 2.70e-02, 1.38e+01, 8.56e+01, 5.14e+01],
       [8.71e-01, 9.60e-02, 4.60e-02, 1.87e+01, 8.91e+01, 5.12e+01],
       [5.02e-01, 4.76e-01, 4.50e-02, 1.65e+01, 7.37e+01, 4.66e+01],
       ...,
       [9.54e-01, 9.00e-03, 9.20e-02, 1.10e+01, 8.92e+01, 4.96e+01],
       [9.48e-01, 8.00e-03, 1.39e-01, 2.01e+01, 9.05e+01, 4.93e+01],
       [9.50e-01, 7.00e-03, 4.20e-02, 1.81e+01, 9.02e+01, 4.74e+01]])